collections:
  - name: community.general
    version: 4.2.0
    source: https://galaxy.ansible.com

  - name: ansible.posix
    version: 1.3.0
    source: https://galaxy.ansible.com

  - name: kubernetes.core
    version: 2.2.2
    source: https://galaxy.ansible.com
