---
- name: Containerd | Include task list in play
  include_tasks: containerd.yml
  tags:
    - containerd
  when: containerd_install | bool

- name: Kubernetes | Include task list in play
  include_tasks: kubernetes-master.yml
  tags:
    - kubernetes
  when: kubernetes_install | bool
